/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthJoinRouteImport } from './routes/_auth/join'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppMembersRouteImport } from './routes/_auth/app/members'
import { Route as ApiDiagramsDiagramIdPresenceRouteImport } from './routes/api/diagrams/$diagramId/presence'
import { Route as ApiDiagramsDiagramIdEventsRouteImport } from './routes/api/diagrams/$diagramId/events'
import { Route as AuthAppDiagramDiagramIdRouteImport } from './routes/_auth/app/diagram.$diagramId'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppMembersRoute = AuthAppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiDiagramsDiagramIdPresenceRoute =
  ApiDiagramsDiagramIdPresenceRouteImport.update({
    id: '/api/diagrams/$diagramId/presence',
    path: '/api/diagrams/$diagramId/presence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiagramsDiagramIdEventsRoute =
  ApiDiagramsDiagramIdEventsRouteImport.update({
    id: '/api/diagrams/$diagramId/events',
    path: '/api/diagrams/$diagramId/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAppDiagramDiagramIdRoute = AuthAppDiagramDiagramIdRouteImport.update({
  id: '/diagram/$diagramId',
  path: '/diagram/$diagramId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/join': typeof AuthJoinRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/members': typeof AuthAppMembersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/diagram/$diagramId': typeof AuthAppDiagramDiagramIdRoute
  '/api/diagrams/$diagramId/events': typeof ApiDiagramsDiagramIdEventsRoute
  '/api/diagrams/$diagramId/presence': typeof ApiDiagramsDiagramIdPresenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof AuthJoinRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/members': typeof AuthAppMembersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/diagram/$diagramId': typeof AuthAppDiagramDiagramIdRoute
  '/api/diagrams/$diagramId/events': typeof ApiDiagramsDiagramIdEventsRoute
  '/api/diagrams/$diagramId/presence': typeof ApiDiagramsDiagramIdPresenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/join': typeof AuthJoinRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/app/members': typeof AuthAppMembersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/diagram/$diagramId': typeof AuthAppDiagramDiagramIdRoute
  '/api/diagrams/$diagramId/events': typeof ApiDiagramsDiagramIdEventsRoute
  '/api/diagrams/$diagramId/presence': typeof ApiDiagramsDiagramIdPresenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/join'
    | '/login'
    | '/signup'
    | '/app/members'
    | '/api/auth/$'
    | '/app/'
    | '/app/diagram/$diagramId'
    | '/api/diagrams/$diagramId/events'
    | '/api/diagrams/$diagramId/presence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/signup'
    | '/app/members'
    | '/api/auth/$'
    | '/app'
    | '/app/diagram/$diagramId'
    | '/api/diagrams/$diagramId/events'
    | '/api/diagrams/$diagramId/presence'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_auth/join'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/app/members'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/diagram/$diagramId'
    | '/api/diagrams/$diagramId/events'
    | '/api/diagrams/$diagramId/presence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDiagramsDiagramIdEventsRoute: typeof ApiDiagramsDiagramIdEventsRoute
  ApiDiagramsDiagramIdPresenceRoute: typeof ApiDiagramsDiagramIdPresenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/join': {
      id: '/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthJoinRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/members': {
      id: '/_auth/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AuthAppMembersRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/diagrams/$diagramId/presence': {
      id: '/api/diagrams/$diagramId/presence'
      path: '/api/diagrams/$diagramId/presence'
      fullPath: '/api/diagrams/$diagramId/presence'
      preLoaderRoute: typeof ApiDiagramsDiagramIdPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagrams/$diagramId/events': {
      id: '/api/diagrams/$diagramId/events'
      path: '/api/diagrams/$diagramId/events'
      fullPath: '/api/diagrams/$diagramId/events'
      preLoaderRoute: typeof ApiDiagramsDiagramIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/diagram/$diagramId': {
      id: '/_auth/app/diagram/$diagramId'
      path: '/diagram/$diagramId'
      fullPath: '/app/diagram/$diagramId'
      preLoaderRoute: typeof AuthAppDiagramDiagramIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppMembersRoute: typeof AuthAppMembersRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppDiagramDiagramIdRoute: typeof AuthAppDiagramDiagramIdRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppMembersRoute: AuthAppMembersRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppDiagramDiagramIdRoute: AuthAppDiagramDiagramIdRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthJoinRoute: typeof AuthJoinRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthJoinRoute: AuthJoinRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDiagramsDiagramIdEventsRoute: ApiDiagramsDiagramIdEventsRoute,
  ApiDiagramsDiagramIdPresenceRoute: ApiDiagramsDiagramIdPresenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
